version: '3.8'

services:
  minio:
    image: minio/minio:latest                                    # init image `minio/minio:latest`
    container_name: minio                                        #container name 'minio'
    restart: unless-stopped                                              #Specify the restart policy after the container exits to always restart, but do not consider containers that have been stopped when the Docker daemon is started.
    environment: # set env,Equivalent to -e in the docker run command
      TZ: Europe/Moscow
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data  --console-address ":9001"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports: #mapping port
      - "9000:9000" # file upload&preview port
      - "9001:9001" # console access port
  database:
    image: 'pgvector/pgvector:pg17'
    container_name: pgvector-ocr-uni
    restart: always
    environment:
      - 'POSTGRES_DB=ocr'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    networks:
      - ocr
networks:
  ocr:
    driver: bridge

volumes:
  pgvector-data: